Repository SOMA-TIL/TIL-Backend, pull requests merged in 2024-11, with the labels that each got.

#104 [TIL-292] 문제 조회 히스토리 남기기 기능 구현
  db/table_ddl.sql
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/config/aspect/HistoryLogAspect.java
  til-domain/src/main/java/com/til/config/model/BaseCreatedTimeEntity.java
  til-domain/src/main/java/com/til/domain/history/annotation/LogProblemViewHistory.java
  til-domain/src/main/java/com/til/domain/history/enums/ActionType.java
  til-domain/src/main/java/com/til/domain/history/model/Histories.java
  til-domain/src/main/java/com/til/domain/history/repository/HistoriesRepository.java
Labels: ✨ feature

#107 [TIL-299] 모의 면접 조회/풀이 API 구조 리팩토링
  db/table_ddl.sql
  til-api/src/main/java/com/til/controller/interview/response/InterviewInfoResponse.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewInfoDto.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewProblemQuestionDto.java
  til-domain/src/main/java/com/til/domain/interview/model/ExperienceInterviewProblem.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepository.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/interview/repository/SpeechInterviewProblemRepository.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: 🛠 refactor

#109 [TIL-300] 면접 문제풀이 테이블 통합 리팩토링
  db/dummy_insert.sql
  db/table_ddl.sql
  til-api/src/main/java/com/til/controller/mock/MockController.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/interview/dto/CreatingProblemResultData.java
  til-domain/src/main/java/com/til/domain/interview/dto/CreatingProblemResultDto.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewProblemQuestionDto.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewProblemSnapshotDto.java
  til-domain/src/main/java/com/til/domain/interview/model/InterviewProblem.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepository.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/interview/repository/ExperienceInterviewProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: 🛠 refactor

#110 [TIL-308] 인터뷰 채점 요청시 필요 정보 수정
  til-domain/src/main/java/com/til/domain/grading/repository/GradingRepositoryCustomImpl.java
Labels: 🛠 refactor

#112 [TIL-310] gateway cors 발생 오류 임시 해결
  til-gateway/src/main/java/com/til/PreFlightCorsConfiguration.java
Labels: 🐞bug
