Repository SOMA-TIL/TIL-Backend, pull requests merged in 2024-08, with the labels that each got.

#38 [TIL-135] 닉네임 검증 API url 변경
  til-api/src/main/java/com/til/config/security/PathPermission.java
  til-api/src/main/java/com/til/controller/user/UserController.java
Labels: 🛠 refactor

#39 [TIL-136] 사용자 정보 검증 로직 메서드 분리
  til-domain/src/main/java/com/til/application/user/UserService.java
  til-domain/src/main/java/com/til/domain/user/validator/UserInfoValidator.java
  til-domain/src/test/java/com/til/domain/user/validator/UserInfoValidatorTest.java
Labels: 🛠 refactor

#42 [TIL-131] 문제 리스트 페이징 리팩토링
  til-api/src/main/java/com/til/common/page/PageParamRequest.java
  til-api/src/main/java/com/til/common/page/PageResponse.java
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-api/src/main/java/com/til/controller/problem/response/ProblemPageResponse.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/domain/common/dto/PageInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemPageDto.java
  til-domain/src/test/java/com/til/application/problem/ProblemServiceTest.java
Labels: 🛠 refactor

#45 [TIL-157] 누락된 public 경로 추가
  til-api/src/main/java/com/til/config/security/AuthenticationFilter.java
  til-api/src/main/java/com/til/config/security/PathPermission.java
Labels: 🛠 refactor

#47 [TIL-127] 모의 면접 생성 기능 구현
  db/table_ddl.sql
  til-api/src/main/java/com/til/controller/interview/InterviewController.java
  til-api/src/main/java/com/til/controller/interview/request/InterviewCreateRequest.java
  til-api/src/main/java/com/til/controller/interview/response/InterviewUuidResponse.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewCreateDto.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewUuidDto.java
  til-domain/src/main/java/com/til/domain/interview/enums/InterviewSuccessCode.java
  til-domain/src/main/java/com/til/domain/interview/model/Interview.java
  til-domain/src/main/java/com/til/domain/interview/model/InterviewStatus.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepository.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: ✨ feature

#48 [TIL-167] Entity 클래스 set로직 제거
  til-domain/src/main/java/com/til/application/problem/SolveProblemService.java
  til-domain/src/main/java/com/til/application/user/UserService.java
  til-domain/src/main/java/com/til/domain/problem/dto/SolveProblemStatusDto.java
  til-domain/src/main/java/com/til/domain/problem/model/UserProblem.java
  til-domain/src/main/java/com/til/domain/user/dto/UserJoinDto.java
  til-domain/src/main/java/com/til/domain/user/model/User.java
  til-domain/src/test/java/com/til/application/problem/SolveProblemServiceTest.java
Labels: 🛠 refactor

#54 [TIL-174] Interview 고유 code 생성 코드 작성
  db/dummy_insert.sql
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/config/utils/Base64Config.java
  til-domain/src/main/java/com/til/config/utils/RandomConfig.java
  til-domain/src/main/java/com/til/domain/interview/enums/InterviewErrorCode.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepository.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/utils/random/RandomValueGenerator.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
  til-domain/src/test/java/com/til/utils/random/RandomValueGeneratorTest.java
Labels: ✨ feature

#53 [TIL-171] 닉네임 변경 API 구현
  til-api/src/main/java/com/til/controller/user/UserController.java
  til-api/src/main/java/com/til/controller/user/request/UserNicknameRequest.java
  til-domain/src/main/java/com/til/application/user/UserService.java
  til-domain/src/main/java/com/til/domain/user/enums/UserSuccessCode.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/user/UserServiceTest.java
Labels: ✨ feature

#50 [TIL-169] 기술학습 문제 상세 정보에 즐겨찾기 정보 추가
  db/dummy_insert.sql
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-domain/src/main/java/com/til/application/auth/AuthService.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemInfoDto.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustomImpl.java
Labels: 🛠 refactor

#55 [TIL-168] 기술학습 문제 답변 제출 히스토리 API 구현
  db/dummy_insert.sql
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-api/src/main/java/com/til/controller/problem/response/ProblemSubmitHistory.java
  til-domain/src/main/java/com/til/application/problem/SolveProblemService.java
  til-domain/src/main/java/com/til/domain/problem/dto/SubmitHistoryDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/SubmitResultDto.java
  til-domain/src/main/java/com/til/domain/problem/enums/ProblemSuccessCode.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepository.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/problem/repository/UserProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/problem/repository/UserProblemRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/problem/SolveProblemServiceTest.java
Labels: ✨ feature

#57 [TIL-176] InterviewCategory 생성 코드 작성
  db/table_ddl.sql
  til-api/src/main/java/com/til/controller/interview/InterviewController.java
  til-api/src/main/java/com/til/controller/interview/request/InterviewCreateRequest.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/category/dto/InterviewCategoryDto.java
  til-domain/src/main/java/com/til/domain/category/model/InterviewCategory.java
  til-domain/src/main/java/com/til/domain/category/repository/InterviewCategoryRepository.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewCreateDto.java
  til-domain/src/main/java/com/til/domain/interview/enums/InterviewErrorCode.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: ✨ feature

#58 [TIL-188] presentation 레이어 조건 분기 application 레이어로 이동
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/test/java/com/til/application/problem/ProblemServiceTest.java
Labels: 🛠 refactor

#61 [TIL-190] InterviewProblem 생성 코드 작성
  db/table_ddl.sql
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/category/repository/ProblemCategoryRepository.java
  til-domain/src/main/java/com/til/domain/category/repository/ProblemCategoryRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/category/repository/ProblemCategoryRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/interview/model/InterviewProblem.java
  til-domain/src/main/java/com/til/domain/interview/model/InterviewProblemStatus.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewProblemRepository.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: ✨ feature

#64 [TIL-209] 기술학습 문제 리스트 쿼리에서 카테고리 join 제거
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemBasicInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemOverviewInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
Labels: 🛠 refactor

#66 [TIL-212] webflux dependency 관련 apple 호환 오류 설정 추가
  til-domain/build.gradle
Labels: 🐞bug, ⚙️ setting

#67 [TIL-213] 기술학습 리스트 페이징 정렬 기능 추가
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
Labels: ✨ feature

#68 [TIL-121] 기술학습 리스트 사용자 정보(즐겨찾기 유무, PASS 여부) 추가
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/domain/auth/dto/AuthUserInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemOverviewInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemUserStatusDto.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemQueryCondition.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/problem/ProblemServiceTest.java
Labels: ✨ feature

#69 [TIL-217] 기술학습 리스트 사용자 답변 제출 여부 정보 추가
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemUserStatusDto.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
Labels: ✨ feature

#72 [TIL-223] 채점 mock api 결과 랜덤 반환
  til-api/src/main/java/com/til/controller/mock/MockController.java
Labels: ⚙️ setting

#70 [TIL-201] 모의면접 답변 제출 API 구현
  til-api/src/main/java/com/til/controller/interview/InterviewController.java
  til-api/src/main/java/com/til/controller/interview/request/InterviewCreateRequest.java
  til-api/src/main/java/com/til/controller/interview/request/InterviewSolveRequest.java
  til-api/src/main/java/com/til/controller/interview/response/InterviewInfoResponse.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewInfoDto.java
  til-domain/src/main/java/com/til/domain/interview/dto/InterviewSolveDto.java
  til-domain/src/main/java/com/til/domain/interview/enums/InterviewErrorCode.java
  til-domain/src/main/java/com/til/domain/interview/enums/InterviewSuccessCode.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewProblemRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewProblemRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: ✨ feature

#71 [TIL-220] 기술학습 문제 리스트/상세 통계(완료한 사람, 정답률) 정보 추가
  db/table_ddl.sql
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemBasicInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemOverviewInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemPublicInfoDto.java
  til-domain/src/main/java/com/til/domain/problem/model/ProblemStatistics.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemQueryCondition.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
Labels: ✨ feature

#78 [TIL-231] 모의면접 채점 결과 사용자 답변 정보 추가
  til-domain/src/main/java/com/til/domain/grading/dto/GradingResultWithProblemInfoDto.java
  til-domain/src/main/java/com/til/domain/grading/repository/GradingRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
Labels: 🛠 refactor

#79 [TIL-233] 기술학습 문제 리스트 즐겨찾기 검색 조건 추가
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-api/src/main/java/com/til/controller/problem/request/SearchProblemRequest.java
  til-domain/src/main/java/com/til/domain/problem/dto/ProblemSearchDto.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemQueryCondition.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/utils/data/BooleanUtil.java
Labels: ✨ feature

#80 [TIL-248] 페이징 파라미터 validation ServiceDto로 변환될 때 수행되도록 수정
  til-api/src/main/java/com/til/common/page/PageParamRequest.java
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
Labels: 🛠 refactor

#81 [TIL-252] domain 모듈 환경변수 property 파일 분리
  til-domain/src/main/java/com/til/application/auth/AuthService.java
  til-domain/src/main/java/com/til/application/grading/GradingService.java
  til-domain/src/main/java/com/til/config/db/RedisConfig.java
  til-domain/src/main/java/com/til/config/properties/GradingApiProperties.java
  til-domain/src/main/java/com/til/config/properties/JwtProperties.java
  til-domain/src/main/java/com/til/config/properties/RedisProperties.java
  til-domain/src/main/java/com/til/domain/auth/provider/TokenProvider.java
  til-domain/src/test/java/com/til/domain/auth/provider/TokenProviderTest.java
Labels: 🛠 refactor
