Repository SOMA-TIL/TIL-Backend, pull requests merged in 2024-09, with the labels that each got.

#82 [TIL-255] ProblemStatistics 엔티티의 필드를 기준으로 정렬 조건 추가
  til-domain/src/main/java/com/til/domain/problem/enums/ProblemSortCriteria.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
Labels: ✨ feature

#86 [TIL-266] 내 정보 가져오기 API 구현
  til-api/src/main/java/com/til/controller/user/UserController.java
  til-api/src/main/java/com/til/controller/user/response/UserInfoResponse.java
  til-domain/src/main/java/com/til/application/user/UserService.java
  til-domain/src/main/java/com/til/domain/user/dto/UserInfoDto.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustom.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepositoryCustomImpl.java
  til-domain/src/test/java/com/til/application/user/UserServiceTest.java
Labels: ✨ feature

#87 [TIL-267] Service Discovery 서버를 위한 til-discovery 모듈 생성
  .gitignore
  build.gradle
  settings.gradle
  til-discovery/build.gradle
  til-discovery/src/main/java/com/example/tildiscovery/TilDiscoveryApplication.java
  til-discovery/src/main/resources/application.yml
Labels: ⚙️ setting

#89 [TIL-269] config 서버를 위한 til-config 모듈 생성
  settings.gradle
  til-config/build.gradle
  til-config/src/main/java/com/example/config/ConfigServiceApplication.java
  til-config/src/main/resources/application-template.yml
Labels: ⚙️ setting

#92 [TIL-273] 공통화 가능한 설정 파일 til-common 모듈로 분리
  til-admin-api/src/main/java/com/til/AdminApiApplication.java
  til-admin-api/src/main/java/com/til/config/WebConfig.java
  til-api/src/main/java/com/til/ApiApplication.java
  til-api/src/main/java/com/til/common/page/PageParamRequest.java
  til-api/src/main/java/com/til/config/AppConfig.java
  til-api/src/main/java/com/til/config/WebConfig.java
  til-api/src/main/java/com/til/config/resolver/CurrentUserResolver.java
  til-api/src/main/java/com/til/config/security/AuthenticationFilter.java
  til-api/src/main/java/com/til/config/security/SecurityConfig.java
  til-api/src/main/java/com/til/controller/problem/request/SearchProblemRequest.java
  til-common/build.gradle
  til-common/src/main/java/com/til/common/config/async/AsyncConfig.java
  til-common/src/main/java/com/til/common/config/helper/Base64Config.java
  til-common/src/main/java/com/til/common/config/helper/PasswordConfig.java
  til-common/src/main/java/com/til/common/config/helper/RandomConfig.java
  til-common/src/main/java/com/til/common/http/cors/BasicCorsConfig.java
  til-common/src/main/java/com/til/common/http/cors/ReactiveCorsConfig.java
  til-common/src/main/java/com/til/common/utils/data/BooleanUtil.java
  til-common/src/main/java/com/til/common/utils/data/ListUtil.java
  til-common/src/main/java/com/til/common/utils/data/StringUtil.java
  til-common/src/main/java/com/til/common/utils/random/RandomValueGenerator.java
  til-common/src/test/java/com/til/common/utils/random/RandomValueGeneratorTest.java
  til-domain/src/main/java/com/til/application/interview/InterviewService.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/application/problem/SolveProblemService.java
  til-domain/src/main/java/com/til/application/user/UserService.java
  til-domain/src/main/java/com/til/config/model/BaseTimeEntity.java
  til-domain/src/main/java/com/til/domain/category/model/Category.java
  til-domain/src/main/java/com/til/domain/category/model/InterviewCategory.java
  til-domain/src/main/java/com/til/domain/category/model/ProblemCategory.java
  til-domain/src/main/java/com/til/domain/common/exception/BaseException.java
  til-domain/src/main/java/com/til/domain/common/exception/InvalidDtoException.java
  til-domain/src/main/java/com/til/domain/grading/model/Grading.java
  til-domain/src/main/java/com/til/domain/grading/repository/GradingRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/interview/model/Interview.java
  til-domain/src/main/java/com/til/domain/interview/model/InterviewProblem.java
  til-domain/src/main/java/com/til/domain/interview/repository/InterviewRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/problem/model/FavoriteProblem.java
  til-domain/src/main/java/com/til/domain/problem/model/Problem.java
  til-domain/src/main/java/com/til/domain/problem/model/UserProblem.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepository.java
  til-domain/src/main/java/com/til/domain/problem/repository/ProblemRepositoryCustomImpl.java
  til-domain/src/main/java/com/til/domain/user/model/User.java
  til-domain/src/main/java/com/til/domain/user/repository/UserRepository.java
  til-domain/src/main/java/com/til/domain/user/validator/UserInfoValidator.java
  til-domain/src/test/java/com/til/application/interview/InterviewServiceTest.java
  til-domain/src/test/java/com/til/application/problem/ProblemServiceTest.java
  til-domain/src/test/java/com/til/application/problem/SolveProblemServiceTest.java
  til-domain/src/test/java/com/til/application/user/UserServiceTest.java
  til-domain/src/test/java/com/til/domain/user/validator/UserInfoValidatorTest.java
  til-gateway/src/main/java/com/til/ApiGatewayApplication.java
  til-gateway/src/main/java/com/til/filter/AuthorizationHeaderFilter.java
Labels: 🛠 refactor

#94 [TIL-277] gateway 인증 필터 사용자 정보 다른 모듈로 전달
  til-admin-api/src/main/java/com/til/AdminApiApplication.java
  til-admin-api/src/main/java/com/til/config/ResolverConfig.java
  til-admin-api/src/main/java/com/til/config/WebConfig.java
  til-admin-api/src/main/java/com/til/config/resolver/CurrentAdminResolver.java
  til-admin-api/src/main/java/com/til/config/security/AuthenticationDeniedHandler.java
  til-admin-api/src/main/java/com/til/config/security/AuthenticationFilter.java
  til-admin-api/src/main/java/com/til/config/security/SecurityConfig.java
  til-admin-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-api/src/main/java/com/til/ApiApplication.java
  til-api/src/main/java/com/til/common/annotation/CurrentUser.java
  til-api/src/main/java/com/til/config/ResolverConfig.java
  til-api/src/main/java/com/til/config/WebConfig.java
  til-api/src/main/java/com/til/config/resolver/CurrentUserResolver.java
  til-api/src/main/java/com/til/config/security/AuthenticationDeniedHandler.java
  til-api/src/main/java/com/til/config/security/AuthenticationFilter.java
  til-api/src/main/java/com/til/config/security/PathPermission.java
  til-api/src/main/java/com/til/controller/auth/AuthController.java
  til-api/src/main/java/com/til/controller/interview/InterviewController.java
  til-api/src/main/java/com/til/controller/problem/ProblemController.java
  til-api/src/main/java/com/til/controller/user/UserController.java
  til-auth/src/main/java/com/til/controller/AuthController.java
  til-common/src/main/java/com/til/common/http/auth/annotation/CurrentUser.java
  til-common/src/main/java/com/til/common/http/auth/enums/AuthConstants.java
  til-common/src/main/java/com/til/common/http/resolver/CurrentUserResolver.java
  til-common/src/main/java/com/til/common/http/security/SecurityConfig.java
  til-domain/src/main/java/com/til/application/auth/AuthService.java
  til-domain/src/main/java/com/til/application/grading/GradingService.java
  til-domain/src/main/java/com/til/application/problem/ProblemService.java
  til-domain/src/main/java/com/til/domain/auth/dto/AuthUserInfoDto.java
  til-gateway/src/main/java/com/til/filter/AuthorizationHeaderFilter.java
Labels: ✨ feature, 🛠 refactor

#95 [TIL-279] til-api 모듈 內 인증/인가 관련 요청 제거
  til-api/src/main/java/com/til/controller/auth/AuthController.java
  til-api/src/main/java/com/til/controller/auth/response/AuthTokenResponse.java
  til-api/src/main/java/com/til/controller/user/UserController.java
Labels: 🛠 refactor

#97 [TIL-281] CI/CD gradle caching 설정 추가
  .github/workflows/cd-dev.yml
  .github/workflows/ci-build-test.yml
Labels: 🛠 refactor

#96 [TIL-278] 변경된 모듈만 CD 빌드 및 도커 작업 진행
  .github/workflows/cd-dev.yml
  docker/Dockerfile
  docker/README.md
  til-api/Dockerfile
Labels: 🛠 refactor
